// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7t6fafoVnE7Oq3LSvIepdcwvD1_8IkTE',
    appId: '1:364492456565:web:432de687e7ab4c5ec26e3c',
    messagingSenderId: '364492456565',
    projectId: 'breastonco-ba797',
    authDomain: 'breastonco-ba797.firebaseapp.com',
    storageBucket: 'breastonco-ba797.appspot.com',
    measurementId: 'G-71VLZKX57L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNIoRJiqyq337wEIY6VL88iM7OD33ukzk',
    appId: '1:364492456565:android:bc4334abb8adf4c0c26e3c',
    messagingSenderId: '364492456565',
    projectId: 'breastonco-ba797',
    storageBucket: 'breastonco-ba797.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw04QLrIAO67WMC56va3M8DJgowd-TVbQ',
    appId: '1:364492456565:ios:75f52425feff9cb1c26e3c',
    messagingSenderId: '364492456565',
    projectId: 'breastonco-ba797',
    storageBucket: 'breastonco-ba797.appspot.com',
    iosBundleId: 'com.example.breastOnco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw04QLrIAO67WMC56va3M8DJgowd-TVbQ',
    appId: '1:364492456565:ios:d7f67b1cc28efe33c26e3c',
    messagingSenderId: '364492456565',
    projectId: 'breastonco-ba797',
    storageBucket: 'breastonco-ba797.appspot.com',
    iosBundleId: 'com.example.breastOnco.RunnerTests',
  );
}
